CREATE TABLE IF NOT EXISTS `accounts` (`aid` int(7) NOT NULL auto_increment COMMENT 'account id', `description` text NOT NULL, `currency` int(3) NOT NULL, PRIMARY KEY  (`aid`), KEY `currency` (`currency`) ) ENGINE=MyISAM  DEFAULT CHARSET=latin1;
INSERT INTO `accounts` (`aid`, `description`, `currency`) VALUES (1, 'My very first bank account', 1),(2, 'My second account \\o/', 1),(3, 'Initial account', 1);
CREATE TABLE IF NOT EXISTS `account_links` (`uid` int(7) NOT NULL COMMENT 'the userID that we are linking against',`aid` int(7) NOT NULL COMMENT 'and the account', `canView` smallint(1) NOT NULL default '1', `canEdit` smallint(1) NOT NULL default '0', PRIMARY KEY  (`uid`,`aid`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
INSERT INTO `account_links` (`uid`, `aid`, `canView`, `canEdit`) VALUES (1, 1, 1, 1),(1, 2, 1, 0);
CREATE TABLE IF NOT EXISTS `applications` (`appid` varchar(32) NOT NULL,`appname` varchar(256) NOT NULL,`description` text NOT NULL,PRIMARY KEY  (`appid`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
INSERT INTO `applications` (`appid`, `appname`, `description`) VALUES ('76bc8e562383104023bd8120d01d98a0', 'MyBanco', 'This AppID allows MyBanco to use MyInfo. NOTE: CHANGE THIS KEY FOR PRODUCTION USE!');
CREATE TABLE IF NOT EXISTS `app_ip_acl` (`appid` varchar(32) NOT NULL, `ip` varchar(16) NOT NULL, KEY `appid` (`appid`), KEY `ip` (`ip`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
INSERT INTO `app_ip_acl` (`appid`, `ip`) VALUES ('76bc8e562383104023bd8120d01d98a0', '127.0.0.1'), ('76bc8e562383104023bd8120d01d98a0', '');
CREATE TABLE IF NOT EXISTS `app_user_acl` (`appid` varchar(32) NOT NULL, `user` varchar(32) NOT NULL, `pass` varchar(2048) NOT NULL, `session` varchar(32) NOT NULL, `timeout` varchar(16) NOT NULL ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
INSERT INTO `app_user_acl` (`appid`, `user`, `pass`, `session`, `timeout`) VALUES ('76bc8e562383104023bd8120d01d98a0', 'tim', 'tim', '3b5556873de753e32fb60e10f7a2cc68', '2');
CREATE TABLE IF NOT EXISTS `countries` (`country` int(4) NOT NULL auto_increment, `used` smallint(1) NOT NULL, `countryName` varchar(32) NOT NULL, `contryISOName` varchar(4) NOT NULL, `homePhoneRule` varchar(24) NOT NULL default '+61 (0%1) %8', `mobilePhoneRule` varchar(24) NOT NULL default '+61 [0]4%8', `countryCurrency` int(3) NOT NULL, PRIMARY KEY  (`country`) ) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;
INSERT INTO `countries` (`country`, `used`, `countryName`, `contryISOName`, `homePhoneRule`, `mobilePhoneRule`, `countryCurrency`) VALUES (1, 1, 'Australia', 'AU', '+61 (0%1) %8', '+61 [0]4%8', 1);
CREATE TABLE IF NOT EXISTS `currencies` ( `cid` int(3) NOT NULL auto_increment, `curreny_short` varchar(4) character set latin1 NOT NULL, `curreny_long` varchar(64) character set latin1 NOT NULL, `sign` varchar(3) character set utf8 collate utf8_bin NOT NULL, PRIMARY KEY  (`cid`) ) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
INSERT INTO `currencies` (`cid`, `curreny_short`, `curreny_long`, `sign`) VALUES (1, 'TDL', 'Test Dollars', 0x24);
CREATE TABLE IF NOT EXISTS `sessions` ( `sid` int(7) NOT NULL auto_increment, `session` varchar(32) NOT NULL, `uid` int(7) NOT NULL, `timeout` int(32) NOT NULL, PRIMARY KEY  (`sid`), KEY `timeout` (`timeout`), KEY `uid` (`uid`) ) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
CREATE TABLE IF NOT EXISTS `session_data` ( `sid` int(7) NOT NULL, `name` varchar(8) NOT NULL, `value` varchar(512) NOT NULL, PRIMARY KEY  (`sid`,`name`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `temp_data` ( `tid` varchar(32) NOT NULL, `expire` int(12) NOT NULL, `special` varchar(16) NOT NULL, `uid` int(7) NOT NULL, `extraID` int(2) NOT NULL, `data` text NOT NULL, PRIMARY KEY  (`tid`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `transactions` ( `transactionID` int(8) NOT NULL auto_increment, `transactionTime` varchar(16) NOT NULL, `from_aid` int(7) NOT NULL, `to_aid` int(7) NOT NULL, `amount` decimal(14,4) NOT NULL, `description` text NOT NULL, PRIMARY KEY  (`transactionID`), KEY `from_aid` (`from_aid`,`to_aid`), KEY `transactionTime` (`transactionTime`)) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=10 ;
INSERT INTO `transactions` (`transactionID`, `transactionTime`, `from_aid`, `to_aid`, `amount`, `description`) VALUES (1, '1211108608', 1, 1, '100.0000', 'This was a cool transaction :)'), (2, '1240325116', 1, 2, '75.0000', 'and now I paid bob money'), (3, '1240325216', 1, 3, '40.0000', 'Then I went bankrupt'), (4, '1240325316', 3, 1, '5000.0000', 'This is a API transaction ...'), (5, '1215928310', 1, 2, '50.0000', '\\o/ a transaction'), (6, '1216014740', 1, 2, '75.0000', 'Woo, another one :)'), (7, '1216014740', 2, 1, '20.0000', 'LOLCAT'), (8, '1216183981', 2, 1, '10.0000', 'I need a message here. How stange.'), (9, '1240325416', 1, 2, '125.0000', 'Transfer between accounts.');
CREATE TABLE IF NOT EXISTS `users` (   `uid` int(7) NOT NULL auto_increment,   `username` varchar(16) NOT NULL,   `password` text NOT NULL,   `loginTime` int(8) NOT NULL,   `lastLoginTime` int(8) NOT NULL,   PRIMARY KEY  (`uid`),   UNIQUE KEY `username` (`username`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
INSERT INTO `users` (`uid`, `username`, `password`, `loginTime`, `lastLoginTime`) VALUES (1, 'tim', 'login', 1240325416, 1240325416), (2, 'bob', 'smith', 0, 0);
CREATE TABLE IF NOT EXISTS `user_info` ( `infoid` int(8) NOT NULL auto_increment, `uid` int(7) NOT NULL, `isPrimrary` int(1) NOT NULL,`title` varchar(6) NOT NULL, `firstName` varchar(64) NOT NULL, `lastName` varchar(64) NOT NULL, `addressLine1` varchar(128) NOT NULL, `addressLine2` varchar(128) NOT NULL, `city` varchar(64) NOT NULL, `state` varchar(6) NOT NULL, `zip` int(8) NOT NULL, `country` int(4) NOT NULL, `homePhone` varchar(64) NOT NULL, `mobilePhone` varchar(64) NOT NULL, PRIMARY KEY  (`infoid`), KEY `uid` (`uid`) ) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
INSERT INTO `user_info` (`infoid`, `uid`, `isPrimrary`, `title`, `firstName`, `lastName`, `addressLine1`, `addressLine2`, `city`, `state`, `zip`, `country`, `homePhone`, `mobilePhone`) VALUES (1, 1, 1, 'Mr', 'Tim', 'Lastname', '9 Humor Close', '', 'Thereland', 'CA', 1234, 1, '', ''),(2, 2, 1, 'Mr', 'Bob', 'Smith', '21 Funny Street', '', 'SomewhereLand', 'NSW', 2284, 1, '', '');
CREATE TABLE `admins` (`uid` INT( 7 ) NOT NULL , `admingroup` INT( 4 ) NOT NULL) ENGINE = MYISAM ;
INSERT INTO `admins` (`uid` , `admingroup`) VALUES ('1', '-1');
CREATE TABLE IF NOT EXISTS `stock_tickers` (`stockid` int(5) NOT NULL auto_increment,`ticker` varchar(4) NOT NULL,`compayName` varchar(128) NOT NULL,`companyDescription` text NOT NULL,PRIMARY KEY  (`stockid`),KEY `ticker` (`ticker`)) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
ALTER TABLE `stock_tickers` ADD `finishedIPO` TINYINT( 1 ) NOT NULL AFTER `companyDescription` ;
ALTER TABLE `stock_tickers` ADD INDEX ( `finishedIPO` );
INSERT INTO `stock_tickers` (`ticker` , `compayName` ,`companyDescription` , `finishedIPO`) VALUES ('ABC','Another Big Company', 'Another Big Company Inc. maintains an index of Websites and other online content, and makes this information freely available to anyone with an Internet connection. The Company''s automated search technology helps people obtain nearly instant access to relevant information from its online index', '0');
ALTER TABLE `stock_tickers` ADD `IPO_offers` INT( 11 ) NOT NULL AFTER `finishedIPO`;
ALTER TABLE `stock_tickers` ADD `IPOprice` DECIMAL( 14, 4 ) NOT NULL AFTER `IPO_offers` ;
UPDATE `stock_tickers` SET `IPO_offers` = '10000' WHERE `stock_tickers`.`stockid` =1 LIMIT 1;
UPDATE `stock_tickers` SET `IPOprice` = '12.0000' WHERE `stock_tickers`.`stockid` =1 LIMIT 1;
CREATE TABLE `stock_ipo_registration` (`stockid` INT( 5 ) NOT NULL ,`userid` INT( 7 ) NOT NULL ,`volume` INT( 11 ) NOT NULL ,`payWithAccount` INT( 7 ) NOT NULL ,INDEX ( `stockid` ),INDEX ( `payWithAccount` )) ENGINE = MYISAM;
INSERT INTO `stock_ipo_registration` (`stockid`, `userid` , `volume`, `payWithAccount`) VALUES ('1', '1', '1000', 1);
INSERT INTO `stock_tickers` (`ticker` , `compayName` , `companyDescription` , `finishedIPO` , `IPO_offers` , `IPOprice` ) VALUES ('SDC', 'Super Big Corporation', 'Super Big Corporation (SBC) is a global Internet brand. The Company''s offerings to users fall into five categories: Front Doors; Search; Communications and Communities; Media, and Connected Life', '1', '100', '10.')
CREATE TABLE `config` (`item` VARCHAR( 32 ) NOT NULL , `value` VARCHAR( 256 ) NOT NULL) ENGINE = MYISAM 
INSERT INTO `config` (`item`, `value` ) VALUES ( 'VER', '0.11' );

